import { Puzzle } from "./interface";

const puzzle_config_1: Puzzle = {
    id : 1,
  size: 13,
  config: [
    {
      index: 1,
      cell: 3,
      length: 10,
      hint: "Later on",
      value: "afterwards",
      type: "h",
    },
    {
      index: 7,
      cell: 27,
      length: 7,
      hint: "Fail to care for",
      value: "neglect",
      type: "h",
    },
    {
      index: 8,
      cell: 35,
      length: 4,
      hint: "Compassion",
      value: "pity",
      type: "h",
    },
    {
      index: 10,
      cell: 53,
      length: 4,
      hint: "Comply with orders",
      value: "obey",
      type: "h",
    },
    {
      index: 11,
      cell: 58,
      length: 8,
      hint: "Destroy",
      value: "demolish",
      type: "h",
    },
    {
      index: 13,
      cell: 79,
      length: 6,
      hint: "Mend",
      value: "repair",
      type: "h",
    },
    {
      index: 15,
      cell: 86,
      length: 6,
      hint: "Head count",
      value: "census",
      type: "h",
    },
    {
      index: 17,
      cell: 105,
      length: 8,
      hint: "Carry on",
      value: "continue",
      type: "h",
    },
    {
      index: 18,
      cell: 114,
      length: 4,
      hint: "Gaming stake",
      value: "ante",
      type: "h",
    },
    {
      index: 21,
      cell: 132,
      length: 4,
      hint: "Near",
      value: "nigh",
      type: "h",
    },
    {
      index: 22,
      cell: 137,
      length: 7,
      hint: "Bishop's District",
      value: "diocese",
      type: "h",
    },
    {
      index: 23,
      cell: 158,
      length: 10,
      hint: "Unnecessarily",
      value: "needlessly",
      type: "h",
    },
    {
      index: 1,
      cell: 3,
      length: 5,
      hint: "Debate",
      value: "argue",
      type: "v",
    },
    {
      index: 2,
      cell: 5,
      length: 4,
      hint: "Fastened",
      value: "tied",
      type: "v",
    },
    {
      index: 3,
      cell: 7,
      length: 6,
      hint: "Cad",
      value: "rotter",
      type: "v",
    },
    {
      index: 4,
      cell: 9,
      length: 8,
      hint: "Okayed",
      value: "approved",
      type: "v",
    },
    {
      index: 5,
      cell: 11,
      length: 7,
      hint: "Simple Songs",
      value: "ditties",
      type: "v",
    },
    {
      index: 6,
      cell: 14,
      length: 9,
      hint: "Wrong",
      value: "incorrect",
      type: "v",
    },
    {
      index: 9,
      cell: 52,
      length: 9,
      hint: "Talked very quietly",
      value: "whispered",
      type: "v",
    },
    {
      index: 12,
      cell: 70,
      length: 8,
      hint: "Completed",
      value: "finished",
      type: "v",
    },
    {
      index: 14,
      cell: 81,
      length: 7,
      hint: "Thoughtful",
      value: "pensive",
      type: "v",
    },
    {
      index: 16,
      cell: 98,
      length: 6,
      hint: "Small pool",
      value: "puddle",
      type: "v",
    },
    {
      index: 19,
      cell: 115,
      length: 5,
      hint: "Penurious",
      value: "needy",
      type: "v",
    },
    {
      index: 20,
      cell: 126,
      length: 4,
      hint: "Gaffer",
      value: "boss",
      type: "v",
    },
  ],
};

export const PUZZLES: ReadonlyArray<Puzzle> = [{ ...puzzle_config_1 }];
