import { Puzzle } from "./interface";

const puzzle_config_1: Puzzle = {
  id: 1,
  freezed: true,
  name: "Puzzle 1",
  size: 13,
  config: [
    {
      index: 1,
      cell: 3,
      length: 10,
      hint: "Later on",
      value: "afterwards",
      type: "h",
    },
    {
      index: 7,
      cell: 27,
      length: 7,
      hint: "Fail to care for",
      value: "neglect",
      type: "h",
    },
    {
      index: 8,
      cell: 35,
      length: 4,
      hint: "Compassion",
      value: "pity",
      type: "h",
    },
    {
      index: 10,
      cell: 53,
      length: 4,
      hint: "Comply with orders",
      value: "obey",
      type: "h",
    },
    {
      index: 11,
      cell: 58,
      length: 8,
      hint: "Destroy",
      value: "demolish",
      type: "h",
    },
    {
      index: 13,
      cell: 79,
      length: 6,
      hint: "Mend",
      value: "repair",
      type: "h",
    },
    {
      index: 15,
      cell: 86,
      length: 6,
      hint: "Head count",
      value: "census",
      type: "h",
    },
    {
      index: 17,
      cell: 105,
      length: 8,
      hint: "Carry on",
      value: "continue",
      type: "h",
    },
    {
      index: 18,
      cell: 114,
      length: 4,
      hint: "Gaming stake",
      value: "ante",
      type: "h",
    },
    {
      index: 21,
      cell: 132,
      length: 4,
      hint: "Near",
      value: "nigh",
      type: "h",
    },
    {
      index: 22,
      cell: 137,
      length: 7,
      hint: "Bishop's District",
      value: "diocese",
      type: "h",
    },
    {
      index: 23,
      cell: 158,
      length: 10,
      hint: "Unnecessarily",
      value: "needlessly",
      type: "h",
    },
    {
      index: 1,
      cell: 3,
      length: 5,
      hint: "Debate",
      value: "argue",
      type: "v",
    },
    {
      index: 2,
      cell: 5,
      length: 4,
      hint: "Fastened",
      value: "tied",
      type: "v",
    },
    {
      index: 3,
      cell: 7,
      length: 6,
      hint: "Cad",
      value: "rotter",
      type: "v",
    },
    {
      index: 4,
      cell: 9,
      length: 8,
      hint: "Okayed",
      value: "approved",
      type: "v",
    },
    {
      index: 5,
      cell: 11,
      length: 7,
      hint: "Simple Songs",
      value: "ditties",
      type: "v",
    },
    {
      index: 6,
      cell: 14,
      length: 9,
      hint: "Wrong",
      value: "incorrect",
      type: "v",
    },
    {
      index: 9,
      cell: 52,
      length: 9,
      hint: "Talked very quietly",
      value: "whispered",
      type: "v",
    },
    {
      index: 12,
      cell: 70,
      length: 8,
      hint: "Completed",
      value: "finished",
      type: "v",
    },
    {
      index: 14,
      cell: 81,
      length: 7,
      hint: "Thoughtful",
      value: "pensive",
      type: "v",
    },
    {
      index: 16,
      cell: 98,
      length: 6,
      hint: "Small pool",
      value: "puddle",
      type: "v",
    },
    {
      index: 19,
      cell: 115,
      length: 5,
      hint: "Penurious",
      value: "needy",
      type: "v",
    },
    {
      index: 20,
      cell: 126,
      length: 4,
      hint: "Gaffer",
      value: "boss",
      type: "v",
    },
  ],
};

const puzzle_config_2: Puzzle = {
  id: 2,
  freezed: true,
  name: "Puzzle 2",
  size: 6,
  config: [
    {
      index: 1,
      cell: 2,
      length: 4,
      hint: "Under the weather",
      value: "sick",
      type: "h",
    },
    {
      index: 5,
      cell: 8,
      length: 4,
      hint: "Lines of C or C++",
      value: "code",
      type: "h",
    },
    {
      index: 6,
      cell: 13,
      length: 6,
      hint: "San Diego team that lost to the Phillies in late October",
      value: "padres",
      type: "h",
    },
    {
      index: 8,
      cell: 19,
      length: 6,
      hint: "Grande who famously licked a donut in 2015",
      value: "ariana",
      type: "h",
    },
    {
      index: 9,
      cell: 25,
      length: 6,
      hint: "In the mind",
      value: "mental",
      type: "h",
    },
    {
      index: 10,
      cell: 32,
      length: 4,
      hint: "I have ____ better",
      value: "seen",
      type: "h",
    },
    {
      index: 1,
      cell: 2,
      length: 6,
      hint: "Screams 'Boo!' at someone, maybe",
      value: "scares",
      type: "v",
    },
    {
      index: 2,
      cell: 3,
      length: 6,
      hint: "First-aid-kit liquid",
      value: "iodine",
      type: "v",
    },
    {
      index: 3,
      cell: 4,
      length: 6,
      hint: "Percentage set by a bank",
      value: "cdrate",
      type: "v",
    },
    {
      index: 4,
      cell: 5,
      length: 6,
      hint: "In Living Color creator Wayans",
      value: "keenan",
      type: "v",
    },
    {
      index: 6,
      cell: 13,
      length: 3,
      hint: "Looking for the Jim to my ___",
      value: "pam",
      type: "v",
    },
    {
      index: 7,
      cell: 18,
      length: 3,
      hint: "Vulcano of Impractical Jokers",
      value: "sal",
      type: "v",
    },
  ],
};

const puzzle_config_3: Puzzle = {
  id: 3,
  freezed: true,
  name: "Puzzle 3",
  size: 5,
  config: [
    {
      index: 1,
      cell: 2,
      length: 4,
      hint: "Bandage that might be signed",
      value: "cast",
      type: "h",
    },
    {
      index: 5,
      cell: 6,
      length: 5,
      hint: "Pop musician ___ Rae Jepsen",
      value: "carly",
      type: "h",
    },
    {
      index: 6,
      cell: 11,
      length: 5,
      hint: "Sans-serif font that resembles Helvetica",
      value: "arial",
      type: "h",
    },
    {
      index: 7,
      cell: 16,
      length: 5,
      hint: "Garbage",
      value: "waste",
      type: "h",
    },
    {
      index: 8,
      cell: 21,
      length: 5,
      hint: "Direct, as a go-kart",
      value: "steer",
      type: "h",
    },
    {
      index: 1,
      cell: 2,
      length: 5,
      hint: "One of 24 for pure gold",
      value: "carat",
      type: "v",
    },
    {
      index: 2,
      cell: 3,
      length: 5,
      hint: "Should the need ___",
      value: "arise",
      type: "v",
    },
    {
      index: 3,
      cell: 4,
      length: 5,
      hint: "List of candidates, or a shade of gray",
      value: "stale",
      type: "v",
    },
    {
      index: 4,
      cell: 5,
      length: 5,
      hint: "Boo! A Madea Halloween star Perry",
      value: "tyler",
      type: "v",
    },
    {
      index: 5,
      cell: 6,
      length: 4,
      hint: "Crow sounds",
      value: "caws",
      type: "v",
    },
  ],
};

const puzzle_config_4: Puzzle = {
  freezed: true,
  id: 4,
  name: "Puzzle 4",
  size: 6,
  config: [
    {
      cell: 4,
      hint: "___ Pepper's Lonely Hearts Club Band",
      index: 1,
      length: 3,
      type: "h",
      value: "sgt",
    },
    {
      cell: 8,
      hint: "It beats rock but loses to scissors",
      index: 4,
      length: 5,
      type: "h",
      value: "paper",
    },
    {
      cell: 14,
      hint: "Repay for one's sins",
      index: 6,
      length: 5,
      type: "h",
      value: "atone",
    },
    {
      cell: 19,
      hint: "Actress Song of Dollface and The Suite Life of Zack & Cody",
      index: 7,
      length: 6,
      type: "h",
      value: "brenda",
    },
    {
      cell: 25,
      hint: "Formed a picture of",
      index: 8,
      length: 6,
      type: "h",
      value: "imaged",
    },
    {
      cell: 31,
      hint: "Fortnite fans, maybe",
      index: 9,
      length: 6,
      type: "h",
      value: "gamers",
    },
    {
      cell: 4,
      hint: "Cleaning product sold by Scrub Daddy",
      index: 1,
      length: 6,
      type: "v",
      value: "sponge",
    },
    {
      cell: 5,
      hint: " Word before identity or spectrum",
      index: 2,
      length: 6,
      type: "v",
      value: "gender",
    },
    {
      cell: 6,
      hint: "Patterns on tires",
      index: 3,
      length: 6,
      type: "v",
      value: "treads",
    },
    {
      cell: 8,
      hint: "Italian city that lends its name to a type of cheese",
      index: 4,
      length: 5,
      type: "v",
      value: "parma",
    },
    {
      cell: 9,
      hint: "Mr. T's group",
      index: 5,
      length: 5,
      type: "v",
      value: "ateam",
    },
    {
      cell: 19,
      hint: "Tom Hanks movie that inspired the 2019 movie Little",
      index: 7,
      length: 3,
      type: "v",
      value: "big",
    },
  ],
};

export const PUZZLES: ReadonlyArray<Puzzle> = [
  { ...puzzle_config_1 },
  { ...puzzle_config_2 },
  { ...puzzle_config_3 },
  { ...puzzle_config_4 },
];
